#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfce4-pulseaudio-plugin
Version  : 0.4.3
Release  : 3
URL      : https://archive.xfce.org/src/panel-plugins/xfce4-pulseaudio-plugin/0.4/xfce4-pulseaudio-plugin-0.4.3.tar.bz2
Source0  : https://archive.xfce.org/src/panel-plugins/xfce4-pulseaudio-plugin/0.4/xfce4-pulseaudio-plugin-0.4.3.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfce4-pulseaudio-plugin-data = %{version}-%{release}
Requires: xfce4-pulseaudio-plugin-lib = %{version}-%{release}
Requires: xfce4-pulseaudio-plugin-license = %{version}-%{release}
Requires: xfce4-pulseaudio-plugin-locales = %{version}-%{release}
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : pkgconfig(exo-2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libpulse-mainloop-glib)
BuildRequires : pkgconfig(libwnck-3.0)
BuildRequires : pkgconfig(libxfce4panel-2.0)
BuildRequires : pkgconfig(libxfce4ui-2)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)
BuildRequires : xfce4-dev-tools

%description
Xfce PulseAudio Panel Plugin
============================
https://docs.xfce.org/panel-plugins/xfce4-pulseaudio-plugin

%package data
Summary: data components for the xfce4-pulseaudio-plugin package.
Group: Data

%description data
data components for the xfce4-pulseaudio-plugin package.


%package lib
Summary: lib components for the xfce4-pulseaudio-plugin package.
Group: Libraries
Requires: xfce4-pulseaudio-plugin-data = %{version}-%{release}
Requires: xfce4-pulseaudio-plugin-license = %{version}-%{release}

%description lib
lib components for the xfce4-pulseaudio-plugin package.


%package license
Summary: license components for the xfce4-pulseaudio-plugin package.
Group: Default

%description license
license components for the xfce4-pulseaudio-plugin package.


%package locales
Summary: locales components for the xfce4-pulseaudio-plugin package.
Group: Default

%description locales
locales components for the xfce4-pulseaudio-plugin package.


%prep
%setup -q -n xfce4-pulseaudio-plugin-0.4.3
cd %{_builddir}/xfce4-pulseaudio-plugin-0.4.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1609289183
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --enable-maintainer-mode
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1609289183
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfce4-pulseaudio-plugin
cp %{_builddir}/xfce4-pulseaudio-plugin-0.4.3/COPYING %{buildroot}/usr/share/package-licenses/xfce4-pulseaudio-plugin/ea59e2cd7b05e4c7591f74b3eeb3af61d69f9332
%make_install
%find_lang xfce4-pulseaudio-plugin

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/icons/hicolor/48x48/apps/xfce4-pulseaudio-plugin.png
/usr/share/icons/hicolor/scalable/apps/xfce4-pulseaudio-plugin.svg
/usr/share/icons/hicolor/scalable/status/audio-volume-high-symbolic.svg
/usr/share/icons/hicolor/scalable/status/audio-volume-low-symbolic.svg
/usr/share/icons/hicolor/scalable/status/audio-volume-medium-symbolic.svg
/usr/share/icons/hicolor/scalable/status/audio-volume-muted-symbolic.svg
/usr/share/icons/hicolor/scalable/status/microphone-sensitivity-high-symbolic.svg
/usr/share/icons/hicolor/scalable/status/microphone-sensitivity-low-symbolic.svg
/usr/share/icons/hicolor/scalable/status/microphone-sensitivity-medium-symbolic.svg
/usr/share/icons/hicolor/scalable/status/microphone-sensitivity-muted-symbolic.svg
/usr/share/xfce4/panel/plugins/pulseaudio.desktop

%files lib
%defattr(-,root,root,-)
/usr/lib64/xfce4/panel/plugins/libpulseaudio-plugin.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfce4-pulseaudio-plugin/ea59e2cd7b05e4c7591f74b3eeb3af61d69f9332

%files locales -f xfce4-pulseaudio-plugin.lang
%defattr(-,root,root,-)

