#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 5424026
#
Name     : xfce4-pulseaudio-plugin
Version  : 0.4.9
Release  : 9
URL      : https://archive.xfce.org/src/panel-plugins/xfce4-pulseaudio-plugin/0.4/xfce4-pulseaudio-plugin-0.4.9.tar.bz2
Source0  : https://archive.xfce.org/src/panel-plugins/xfce4-pulseaudio-plugin/0.4/xfce4-pulseaudio-plugin-0.4.9.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfce4-pulseaudio-plugin-data = %{version}-%{release}
Requires: xfce4-pulseaudio-plugin-lib = %{version}-%{release}
Requires: xfce4-pulseaudio-plugin-license = %{version}-%{release}
Requires: xfce4-pulseaudio-plugin-locales = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : file
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(exo-2)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libpulse-mainloop-glib)
BuildRequires : pkgconfig(libwnck-3.0)
BuildRequires : pkgconfig(libxfce4panel-2.0)
BuildRequires : pkgconfig(libxfce4ui-2)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)
BuildRequires : xfce4-dev-tools
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![License](https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://gitlab.xfce.org/panel-plugins/xfce4-pulseaudio-plugin/-/blob/master/COPYING)

%package data
Summary: data components for the xfce4-pulseaudio-plugin package.
Group: Data

%description data
data components for the xfce4-pulseaudio-plugin package.


%package lib
Summary: lib components for the xfce4-pulseaudio-plugin package.
Group: Libraries
Requires: xfce4-pulseaudio-plugin-data = %{version}-%{release}
Requires: xfce4-pulseaudio-plugin-license = %{version}-%{release}

%description lib
lib components for the xfce4-pulseaudio-plugin package.


%package license
Summary: license components for the xfce4-pulseaudio-plugin package.
Group: Default

%description license
license components for the xfce4-pulseaudio-plugin package.


%package locales
Summary: locales components for the xfce4-pulseaudio-plugin package.
Group: Default

%description locales
locales components for the xfce4-pulseaudio-plugin package.


%prep
%setup -q -n xfce4-pulseaudio-plugin-0.4.9
cd %{_builddir}/xfce4-pulseaudio-plugin-0.4.9
pushd ..
cp -a xfce4-pulseaudio-plugin-0.4.9 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735118931
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --enable-maintainer-mode
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --enable-maintainer-mode
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735118931
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfce4-pulseaudio-plugin
cp %{_builddir}/xfce4-pulseaudio-plugin-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xfce4-pulseaudio-plugin/ea59e2cd7b05e4c7591f74b3eeb3af61d69f9332 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
%find_lang xfce4-pulseaudio-plugin
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/icons/hicolor/48x48/apps/xfce4-pulseaudio-plugin.png
/usr/share/icons/hicolor/scalable/apps/xfce4-pulseaudio-plugin.svg
/usr/share/icons/hicolor/scalable/status/audio-volume-high-symbolic.svg
/usr/share/icons/hicolor/scalable/status/audio-volume-low-symbolic.svg
/usr/share/icons/hicolor/scalable/status/audio-volume-medium-symbolic.svg
/usr/share/icons/hicolor/scalable/status/audio-volume-muted-symbolic.svg
/usr/share/icons/hicolor/scalable/status/microphone-sensitivity-high-symbolic.svg
/usr/share/icons/hicolor/scalable/status/microphone-sensitivity-low-symbolic.svg
/usr/share/icons/hicolor/scalable/status/microphone-sensitivity-medium-symbolic.svg
/usr/share/icons/hicolor/scalable/status/microphone-sensitivity-muted-symbolic.svg
/usr/share/xfce4/panel/plugins/pulseaudio.desktop

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/xfce4/panel/plugins/libpulseaudio-plugin.so
/usr/lib64/xfce4/panel/plugins/libpulseaudio-plugin.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfce4-pulseaudio-plugin/ea59e2cd7b05e4c7591f74b3eeb3af61d69f9332

%files locales -f xfce4-pulseaudio-plugin.lang
%defattr(-,root,root,-)

